# vim: ft=yaml
---
driver:
  name: vagrant

provisioner:
  name: salt_solo
  formula: smartmontools
  state_top:
    base:
      "*":
        - smartmontools

platforms:
  - name: bento/debian-8

suites:
  - name: default

  - name: custom
    provisioner:
      pillars-from-files:
        smartmontools.sls: pillar-custom.sls
      pillars:
        top.sls:
          base:
            "*":
              - smartmontools

