# vim: ft=yaml
---
driver:
  name: linode

provisioner:
  name: salt_solo
  formula: smartmontools
  state_top:
    base:
      "*":
        - smartmontools

platforms:
  - name: debian_jessie

suites:
  - name: default

  - name: custom
    provisioner:
      pillars-from-files:
        smartmontools.sls: pillar-custom.sls
      pillars:
        top.sls:
          base:
            "*":
              - smartmontools
